### PR TITLE
Fix/reveal

### LINKED ISSUE #451: [Bug]: Sugar reveal - No URI found
I did a CMv3 guards with hidden setting, i want to test the sugar reveal, but i get this error, what i did wrong? I just follow the guide. 

image

### PR DESCRIPTION
**Pull request by samuelvanderwaal**
Fixes #451 and reveal gPA call.

The last commit decouples the pattern checking logic from the name so the names in the JSON asset files do not have to match the Unrevealed Name Pattern that the NFTs are initially created with. The revealed names also do not have to have the same pattern themselves.

Pre-reveal:
Selection_110

Selection_111

Post-reveal:
Selection_112

Selection_113

If the pattern match fails due to the reveal already happening it prints a warning message but doesn't fail the rest of the reveal:

Selection_114

Finally, it handles NFT naming zero and one indexed by parsing the `$ID*$` pattern in the config file.

### CODE REVIEW

File: src/reveal/process.rs [hunk 1]
```diff
@@ -198,25 +194,15 @@ pub async fn process_reveal(args: RevealArgs) -> Result<()> {
...
-            .split('#')
-            .nth(1)
-            .ok_or_else(|| anyhow!("No NFT number found for name: {name}"))?;
 
         let metadata_pubkey = find_metadata_pda(&m.mint);
         let new_uri = nft_lookup
-            .get(num)
-            .ok_or_else(|| anyhow!("No URI found for number: {num}"))?
+            .get(name.as_str())
+            .ok_or_else(|| anyhow!("No URI found for number: {name}"))?
```
Comment (febo) [inline src/reveal/process.rs:205]: This should say `name` instead of `number`.

**Review by febo — APPROVED** [review]
Nice!
